api/urls.py
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

from .import views

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

from rest_framework.routers import DefaultRouter



schema_view = get_schema_view(
    openapi.Info(
        title="Enventory API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register(r'supplier', views.SupplierViewset, basename='supplier'),
router.register(r'category', views.CategoryViewset, basename='category'),
router.register(r'purchase', views.Purchase_ApiView, basename='purchase'),
router.register(r'customer', views.CustomerViewset, basename='customer'),
router.register(r'sale', views.Sale_ApiView, basename='sale'),


urlpatterns=[
    # path('',views.SwaggerSchemaView.as_view()),
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
    path('items/', views.Item_list_ApiView.as_view(), name='item-list' ),
    path('stock/', views.Add_Stock_ApiView.as_view(), name='add_stock_api' ),
    path('stock/<str:pk>/', views.Stock_Details_ApiView.as_view(), name='details_stock_api' ),

    # path('purchase/', views.Purchase_ApiView.as_view(), name='purchase_api')

]+router.urls

inventory/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls'), name='api'),

]

stock/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.list_items, name='home'),
    # list of items 
    path('items/', views.list_items, name='list_items'),
    path('total_list/', views.total_list, name='total_list'),

    #  Stock Urls 
    path('add_stock/', views.add_stock_form, name='add_stock'),
    path('update_stock/<str:pk>/', views.Update_stock_form, name="update_stock"),
    path('delete_stock/<str:pk>/', views.delete_stock, name="delete_stock"),
    path('stock_details/<str:pk>/', views.stock_details, name="stock_details"),

    # Supplier urls 
    path('add_sup/', views.add_sup_form, name='add_sup'),

    # category urls
    path('add_category/', views.add_catrgory_form, name='add_category'),
    
    # pyrchase urls
    path('purchase/', views.purches, name="purchase"),

    # sales urls
    path('add_cust/', views.add_cust_form, name='add_cust'),
    path('sale/', views.sale, name="sale"),
    path('total_sale/', views.Total_sale.as_view(), name="total_sale"),
    path('sale_details/<str:pk>/', views.Sale_details.as_view(), name="sale_details"),

    path('logout/', views.logoutuser, name="logout"),

   

    
]

stock/models.py
from datetime import timezone
from django.db import models



# Create your models here.

class Category (models.Model):
    cat_name= models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.cat_name


class Supplier (models.Model):
    sup_name = models.CharField(max_length=200, null=True,)
    sup_mobile = models.CharField(max_length=200, null=True, blank=True)
    sup_email = models.CharField(max_length=200, null=True, blank=True)
    sup_note = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.sup_name

class Stock( models.Model):
    id = models.AutoField(primary_key=True)
    category =models.ForeignKey(Category, on_delete=models.SET_NULL, null=True,blank=True)
    item_name = models.CharField(max_length=200, null=True)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(null=True, blank=True,default= 0)
    amount = models.FloatField(null=True, blank=True,default= 0)
    supplier= models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True,blank=True)
    last_updated=models.DateTimeField(auto_now_add=False,auto_now=True)
    timestamp= models.DateTimeField(auto_now_add=True,auto_now=False,)
    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        itemname=str(self.item_name)
        return itemname


class Purches (models.Model):
    id = models.AutoField(primary_key=True)
    supplier = models.ForeignKey (Supplier,on_delete=models.CASCADE)
    stock = stock = models.ForeignKey(Stock, on_delete=models.SET_NULL, null=True, related_name='purchasestock')
    pur_quantity = models.IntegerField( default=0)



class Customer (models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name

class Sale (models.Model):

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    stock = stock = models.ForeignKey(Stock, on_delete=models.SET_NULL, null=True, related_name='salestock')
    sale_quantity = models.IntegerField()
    
    def __str__(self) -> str:
            return str(self.customer)

stock/forms.py
from django import forms
from django.forms import formset_factory
from django.db import models
from django.db.models import fields
from .models import Stock,Supplier,Category,Purches,Sale,Customer

class Add_stock_form (forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['category','item_name', 'quantity','price','amount', 'supplier']

    

class Add_Sup_form (forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['sup_name','sup_mobile','sup_email','sup_note']

class Add_Category_form (forms.ModelForm):
    class Meta:
        model = Category
        fields = ['cat_name']

class PurchesForm(forms.ModelForm):

    def __init__ (self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['stock'].queryset = Stock.objects.filter(is_deleted= False)

    class Meta:
        model = Purches
        fields=['supplier','stock', 'pur_quantity']

Purchase_stock_formset= formset_factory(PurchesForm, extra=1)



class Add_Cust_form (forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class SaleForm(forms.ModelForm):

    def __init__ (self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        self.fields['stock'].queryset = Stock.objects.filter(is_deleted= False)

    class Meta:
        model = Sale
        fields=['customer','stock', 'sale_quantity']

# Purchase_stock_formset= formset_factory(PurchesForm, extra=1)


        

stock/views.py
from django.shortcuts import render ,redirect,get_object_or_404
from .models import *
from .forms import *
from .filters import Filter
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users 

# Templateviews
from django.views.generic import ListView , DetailView


# Create your views here.

@login_required(login_url='user_login')
def home (request):

    return render(request, 'stock/home.html')

@login_required(login_url='user_login')
def list_items(request):

    items = Stock.objects.all()
    supplier=Supplier.objects.all()
    customer = Customer.objects.all()

    total_items= items.count()
    total_supplier = supplier.count()
    total_quantity=[]
    

    for item in items:

        if item.quantity is None:

            item.quantity = 0

            

        else:
            total_quantity.append(item.quantity)
    total_quantity=sum(total_quantity)


    search= Filter(request.GET, queryset=items)

    items = search.qs
    
    

    context = {
    
    'items':items,
    'search':search,
    'total_items':total_items,
    'total_supplier':total_supplier,
    'total_quantity':total_quantity,
    'customer':customer,
    }

    return render (request, 'stock/itmes.html', context)

@login_required(login_url='user_login')
def add_stock_form (request):
    form = Add_stock_form(request.POST)

    if form.is_valid():
        form.save()
        messages.success(request, 'Successfully Added Stock')
        return redirect('list_items')

    context = {
        'form': form,
    }

    return render (request,'stock/add_stock.html',context)


@login_required(login_url='user_login')
def add_sup_form (request):

    form = Add_Sup_form(request.POST or None)

    if form.is_valid():
        form.save()
        
        messages.success(request, 'Successfully Added Supplier')
        return redirect('list_items')
        

    context = {
        'form': form 
    }

    return render (request,'stock/add_sup.html',context)


@login_required(login_url='user_login')
def add_catrgory_form (request):

    form = Add_Category_form(request.POST or None)

    if form.is_valid():
        form.save()
        
        messages.success(request, 'Successfully Added Category')
        return redirect('list_items')
        

    context = {
        'form': form 
    }

    return render (request,'stock/add_category.html',context)


@login_required(login_url='user_login')
def Update_stock_form (request,pk):
    items = Stock.objects.get(id=pk)

    form = Add_stock_form(instance=items)

    if request.method=='POST':

        form = Add_stock_form(request.POST,instance=items)

        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully Updated Stock')
            return redirect('list_items')

    context ={
        'form' : form 
    }

    return render (request,'stock/update_stock.html',context)

@login_required(login_url='user_login')
@allowed_users(allowed_roles=['admin'])
def delete_stock(request, pk):
    item = Stock.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        messages.success(request, 'Successfully Deleted Stock')
        return redirect('list_items')
    return render(request, 'stock/delete_stock.html')


@login_required(login_url='user_login')
def stock_details (request, pk):

    item = Stock.objects.get(id=pk)

    print (item.supplier.sup_mobile)

    context={
        'item':item
    }

    return render (request, 'stock/stock_details.html',context)

@login_required(login_url='user_login')
def total_list(request):

    items = Stock.objects.all()
    suppliers = Supplier.objects.all()
    categories= Category.objects.all()
    customers= Customer.objects.all()

 

    context ={
        'items':items ,
        'suppliers':suppliers,
        'categories':categories,
        'customers':customers
    }

    return render (request, 'stock/total_list.html', context)

@login_required(login_url='user_login')
def logoutuser (request):

    if request.method == 'POST':
        logout(request)
        return redirect('list_items')



def purches ( request):

    if request.method== 'GET':
        formset = Purchase_stock_formset(request.GET or None)

        context ={
            'formset':formset
        }

        return render (request, 'stock/purches.html',context)

    if request.method == 'POST':

        formset = Purchase_stock_formset (request.POST)

        if formset.is_valid():

            for form in formset:

                add_item = form.save(commit= False)

                stock = get_object_or_404 (Stock, item_name = add_item.stock.item_name)

                print ("Stock Item" , stock.quantity)
                print ('Add item', add_item.pur_quantity)

                stock.quantity += add_item.pur_quantity

                stock.save()
                form.save()

            return redirect('home')
        return render (request,'stock/purches.html')


def add_cust_form (request):

    form = Add_Cust_form(request.POST or None)

    if form.is_valid():
        form.save()
        
        messages.success(request, 'Successfully Added Customer')
        return redirect('list_items')
        

    context = {
        'form': form 
    }

    return render (request,'stock/add_cust.html',context)




def sale (request):
    if request.method== 'GET':
            form = SaleForm(request.GET or None)

            context ={
                'form':form
            }
            return render (request, 'stock/sale.html',context)

    if request.method == 'POST':

        form = SaleForm(request.POST)

        if form.is_valid():

            sale_item = form.save(commit=False)
            stock = get_object_or_404(Stock, item_name = sale_item.stock.item_name)
            sale = Sale.objects.all()

            print ("Stock Item ", stock.quantity)
            print('Sale item ', sale_item.sale_quantity)

            stock.quantity -= sale_item.sale_quantity

            stock.save()
            form.save()

        return redirect('home')


            # return render (request, 'stock/sale.html',context)

class Total_sale(ListView):
    template_name = 'stock/total_sale.html'
    queryset = Sale.objects.all()


class Sale_details(DetailView):
    template_name ='stock/sale_details.html'
    queryset=Sale.objects.all()

stock/templates/stock/add_cust.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="">
    <div class=" ">

        <div class="" style="padding-left: 10rem; padding-right: 10rem;">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}

                <script>
                    alert("{{ message }}");
                </script>

                {% endfor %}
            </ul>
            {% endif %}
            <div class="mt-4" role="alert">
                <h2 class="text-center display-4"> <strong> Add Customer Page</strong></h2>
                <hr>
            </div>

            <h3>{{message}}</h3>
            <form action="" method="POST">
                {% csrf_token %}

                {{form|crispy}}

                <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/add_multistock.html
{%extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="">


    <div class="" style="padding-left: 10rem; padding-right: 10rem;">

        <div class="" role="alert">
            <h2 class="text-center display-4 mt-4"> <strong> How Many Items do you want to add ? </strong></h2>
            <hr>
        </div>

        <h3>{{message}}</h3>

        <form action="{% url 'multi_stock' %}" method="GET">
            {% csrf_token %}

            {{form |crispy}}

            <button type="submit" class="btn btn-info ">Submit</button>
        </form>
    </div>

</div>

{% endblock %}

stock/templates/stock/add_stock.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="">


    <div class="" style="padding-left: 10rem; padding-right: 10rem;">

        <div class="" role="alert">
            <h2 class="text-center display-4 mt-4"> <strong> Add Stock Item</strong></h2>
            <hr>
        </div>

        <div>


            <h3>{{message}}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}

                <button type="submit" class="btn btn-info ">Submit</button>
            </form>
        </div>

    </div>

    {% endblock %}

stock/templates/stock/add_sup.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="">
    <div class=" ">

        <div class="" style="padding-left: 10rem; padding-right: 10rem;">

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}

                <script>
                    alert("{{ message }}");
                </script>

                {% endfor %}
            </ul>
            {% endif %}
            <div class="mt-4" role="alert">
                <h2 class="text-center display-4"> <strong> Add Supplier Page</strong></h2>
                <hr>
            </div>

            <h3>{{message}}</h3>
            <form action="" method="POST">
                {% csrf_token %}

                {{form|crispy}}

                <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/home.html
<div>
    <a href="{% url 'list_items'%}">List of Items </a>
    <br>
    <a href="{% url 'add_stock'%}">Add Stock </a>
</div>

stock/templates/stock/itmes.html
{% extends "base.html" %}
{% block title  %} Home {% endblock title%}
{% block content %}
{% load crispy_forms_tags %}
<main>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}

        <script>
            alert("{{ message }}");
        </script>

        {% endfor %}
    </ul>
    {% endif %}


    <div class="container-fluid">
        <h1 class="mt-4 mb-3">Dashboard</h1>
        <hr>
        <div class="row">
            <div class="col-xl-4 col-md-6  text-center">
                <div class="card bg-primary text-white mb-4">
                    <div class="card-body">
                        <h3>Total Stock Items</h3>
                    </div>
                    <div class=" text-center">
                        <h1 class="display-3"><span class="badge badge-light">{{total_items}}</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 text-center">
                <div class="card bg-dark text-white mb-4">
                    <div class="card-body">
                        <h3>Total Suppliers</h3>
                    </div>
                    <div class=" text-center">
                        <h1 class="display-3"><span class="badge badge-light">{{total_supplier}}</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 text-center">
                <div class="card bg-success text-white mb-4">
                    <div class="card-body">
                        <h3>Total Stock Quantity</h3>
                    </div>
                    <div class=" text-center">
                        <h1 class="display-3"><span class="badge badge-light">{{total_quantity}}</span></h1>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">

            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Stock Details
            </div>

            <div class="form-group card mb-4">
                <form class="form-group" action="" method="GET">

                    {% csrf_token %}
                    <br>
                    <div class="text-center">
                        {{search.form}}
                        <input class="btn btn-info pl-4 pr-4" type="submit" value="Search" name="" id="">
                    </div>

                </form>
            </div>

            <div class="card-body">
                <div class="table-responsive">

                    <table class="table table-striped table-dark">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Item Name</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Price</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Supplier</th>
                                <th scope="col">Last-Updated</th>

                                <th scope="col">Update</th>
                                <th scope="col">Delete</th>



                            </tr>
                        </thead>
                        {% for item in items %}
                        <tbody>
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><a href="{% url 'stock_details' item.id %}">{{item.item_name}}</a></td>
                                <td>{{item.quantity}}</td>
                                <td>{{item.price}}</td>
                                <td>{{item.amount}}</td>
                                <td>{{item.supplier}}</td>
                                <td>{{item.last_updated}}</td>

                                <td c><a href="{% url 'update_stock' item.id %}"><button type="button"
                                            class="btn btn-info btn-sm">Update</button></a></td>
                                <td><a href="{% url 'delete_stock' item.id %}"><button type="button"
                                            class="btn btn-danger btn-sm">Delete</button></a></td>
                            </tr>
                        </tbody>
                        {% endfor%}

                    </table>

                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stock/templates/stock/multistock.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="">


    <div class="" style="padding-left: 10rem; padding-right: 10rem;">

        <div class="" role="alert">
            <h2 class="text-center display-4 mt-4"> <strong> Add Multi Stock Item</strong></h2>
            <hr>
        </div>

        <h3>{{message}}</h3>
        <form action="{% url 'multi_stock' %}" method="POST">
            {% csrf_token %}

            {{formset.management_form}}
            {% for form in formset %}
            <h3>Add items {{ forloop.counter }}</h3>
            {{form|crispy}}

            <br>


            {% endfor %}

            <button type="submit" class="btn btn-info ">Submit</button>
        </form>
    </div>

</div>

{% endblock %}

stock/templates/stock/purches.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="">
    <div class=" ">

        <div class="" style="padding-left: 10rem; padding-right: 10rem;">


            <div class="mt-4" role="alert">
                <h2 class="text-center display-4"> <strong> Purches Page</strong></h2>
                <hr>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ formset.management_form|crispy }}

                {% for form in formset %}
                <!-- {{form|crispy}} -->
                <label for="id_supplier">Supplier Name</label>
                {{ form.supplier }}
                <br>
                <label for="id_stock">Item Name</label>
                {{ form.stock }}
                <br>

                <label for="id_pur_quantity">Quantity</label>
                {{ form.pur_quantity }}
                {% endfor %}
                <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/sale.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="">
    <div class=" ">

        <div class="" style="padding-left: 10rem; padding-right: 10rem;">


            <div class="mt-4" role="alert">
                <h2 class="text-center display-4"> <strong> Sale Page</strong></h2>
                <hr>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}


                <button type="submit" class="btn btn-info">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/sale_details.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="text-center mb-4 mt-4">
    <h2 class="display-4 mt-4"> Sale Information </h2>
</div>
<div class="row">

    <div class="col-sm-5 ml-4 ">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Item Name : <strong>{{object.stock.item_name}} </strong></h5>
                <ul class="card-text">
                    <li>Quantity : <strong>{{object.sale_quantity}}</strong></li>

                    <!-- <li>Price : <strong>{{item.price}}</strong></li>
                    <li>Amount : <strong>{{item.amount}}</strong></li> -->

                    <!-- <li>Timestamp : <strong>{{item.timestamp}}</strong></li> -->
                    <!-- <li>Last-Updated : <strong>{{item.last_updated}}</strong></li> -->

                </ul>

            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Customer : <strong>{{object.customer.name}} </strong></h5>
                <ul class="card-text">
                    <li>Phone : <strong>{{object.customer.phone}}</strong></li>

                    <!-- <li>Email : <strong>{{item.supplier.sup_email}}</strong></li>
                    <li>Note : <strong>{{item.supplier.sup_note}}</strong></li> -->



                </ul>

            </div>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/stock_details.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="text-center mb-4 mt-4">
    <h2 class="display-4 mt-4"> Stock Information </h2>
</div>
<div class="row">

    <div class="col-sm-5 ml-4 ">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Item Name : <strong>{{item.item_name}} </strong></h5>
                <ul class="card-text">
                    <li>Quantity : <strong>{{item.quantity}}</strong></li>

                    <li>Price : <strong>{{item.price}}</strong></li>
                    <li>Amount : <strong>{{item.amount}}</strong></li>

                    <li>Timestamp : <strong>{{item.timestamp}}</strong></li>
                    <li>Last-Updated : <strong>{{item.last_updated}}</strong></li>

                </ul>
                <a href="{% url 'update_stock' item.id %}" class="btn btn-info ml-2">Update Stock</a>
                <a href="{% url 'delete_stock' item.id %}" class="btn btn-danger ml-3">Delete Stock</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Supplier : <strong>{{item.supplier.sup_name}} </strong></h5>
                <ul class="card-text">
                    <li>Mobile : <strong>{{item.supplier.sup_mobile}}</strong></li>

                    <li>Email : <strong>{{item.supplier.sup_email}}</strong></li>
                    <li>Note : <strong>{{item.supplier.sup_note}}</strong></li>



                </ul>

            </div>
        </div>
    </div>
</div>

{% endblock %}

stock/templates/stock/total_list.html
{% extends "base.html" %}
{% block title  %} Home {% endblock title%}
{% block content %}
{% load crispy_forms_tags %}
<main>



    <div class="container-fluid">
        <h1 class="mt-4 mb-3">Total Stock List</h1>
        <hr>
        <div class="row mt-4">
            <div class="col-xl-4 col-md-6  text-center mt-4">
                <div class="card bg-dark text-white mb-4">
                    <div class="card-body">
                        <h3>Total Stock Items</h3>
                    </div>
                    <div class=" text-center">

                        <table class="table table-sm table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Item Name</th>
                                    <th scope="col">Quantity</th>
                                </tr>
                            </thead>
                            {% for item in items %}
                            <tbody>
                                <tr>

                                    <td>{{item.item_name}}</td>
                                    <td>{{item.quantity}}</td>
                                </tr>

                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6  text-center mt-4">
                <div class="card bg-dark text-white mb-4">
                    <div class="card-body">
                        <h3>Total Suppliers </h3>
                    </div>
                    <div class=" text-center">

                        <table class="table table-sm table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Supplier Name</th>
                                    <th scope="col">Mobile</th>
                                </tr>
                            </thead>
                            {% for sup in suppliers %}
                            <tbody>
                                <tr>

                                    <td>{{sup.sup_name}}</td>
                                    <td>{{sup.sup_mobile}}</td>
                                </tr>

                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6  text-center mt-4">
                <div class="card bg-dark text-white mb-4">
                    <div class="card-body">
                        <h3>Total Categories </h3>
                    </div>
                    <div class=" text-center">

                        <table class="table table-sm table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Categories</th>

                                </tr>
                            </thead>
                            {% for cat in categories %}
                            <tbody>
                                <tr>

                                    <td>{{cat.cat_name}}</td>

                                </tr>

                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-md-6  text-center mt-4">
                <div class="card bg-dark text-white mb-4">
                    <div class="card-body">
                        <h3>Total Customers </h3>
                    </div>
                    <div class=" text-center">

                        <table class="table table-sm table-dark">
                            <thead>
                                <tr>
                                    <th scope="col">Customer Name</th>
                                    <th scope="col">Mobile</th>

                                </tr>

                            </thead>
                            {% for cust in customers %}
                            <tbody>
                                <tr>

                                    <td>{{cust.name}}</td>
                                    <td>{{cust.phone}}</td>

                                </tr>



                            </tbody>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">

            </div>
        </div>



    </div>
    </div>
    </div>
</main>

{% endblock %}